name: Shortcut notification of next version
description: Change shortcut labels and create the deployment description
branding:
  icon: 'tag'
  color: 'purple'
inputs:
  branch-name:
    description: 'The current branch'
    required: true
  current-version:
    description: 'The current version'
    required: true
  next-version:
    description: 'The next (incremented) version'
    required: true
  shortcut-token:
    description: 'The shortcut token'
    required: true
  github-token:
    description: 'The github token'
    required: true

outputs:
  deployment-description:
    description: 'The deployment description'
runs:
  using: node16
  main: 'dist/index.js'
