name: test-increment-version

on:
  workflow_dispatch:
    inputs:
      current-version:
        description: 'The current version to increment'
        required: true
      version-fragment:
        description: 'The versions fragment to increment. possible options are [ major | feature | fix ]'
        required: true


jobs:
  test-increment-version:
    name: Test version increment for ${{ github.event.inputs.current-version }} fragment ${{ github.event.inputs.version-fragment }}
    runs-on: alpine:3.10
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: .github/clubhouse_commenter
        run: yarn
        env:
          NODE_AUTH_TOKEN: ""