name: Increment Version
description: Bump a given version by a release type ( major | minor | fix )
branding:
  icon: 'tag'
  color: 'purple'
inputs:
  current-version:
    description: 'The current version to increment'
    required: true
  version-fragment:
    description: 'The versions fragment to increment. possible options are [ major | minor | fix ]'
    required: true
outputs:
  next-version:
    description: 'The incremented version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.current-version }}
    - ${{ inputs.version-fragment }}
