name: test-increment-version

on:
  workflow_dispatch:
    inputs:
      current-version-file:
        description: 'The current version file to increment'
        default: 'demo/chem101-server.platform-conventions.gradle'
        required: true
      version-fragment:
        type: choice
        description: 'The type of release: fix, minor or major'
        required: true
        options:
          - fix
          - minor
          - major

jobs:

  test-increment-version:
    name: Test version increment for ${{github.event.inputs.current-version-file}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history for all tags and branches

      - name: Read the branch name
        id: read_current_branch_name
        run: echo ::set-output name=branch-name::${GITHUB_REF#refs/*/}

      - name: Getting current version
        id: read_current_version
        uses: ./.github/actions/read-current-version/
        with:
          current-version-file: ${{github.event.inputs.current-version-file}}

      - name: Increment version ${{ steps.read_current_version.outputs.current-version }}
        id: increment_version
        uses: ./.github/actions/increment-version
        with:
          current-version: ${{ steps.read_current_version.outputs.current-version }}
          version-fragment: ${{ github.event.inputs.version-fragment }} 

#      - name: Commit next version ${{ steps.increment_version.outputs.next-version }}
#        id: commit_next_version
#        uses: ./.github/actions/commit-next-version
#        with:
#          current-version: ${{ steps.read_current_version.outputs.current-version }}
#          next-version: ${{ steps.increment_version.outputs.next-version }}
#          current-version-file: ${{github.event.inputs.current-version-file}}
#        env:
#          BRANCH_NAME: ${{ steps.read_current_branch_name.outputs.branch-name }}

      - name: Shortcut notification for next version ${{ steps.increment_version.outputs.next-version }}
        id: prepare_release_description
        uses: ./.github/actions/shortcut-notify-next-version/
        with:
          branch-name: ${{ steps.read_current_branch_name.outputs.branch-name }}
          current-version: ${{ steps.read_current_version.outputs.current-version }}
          next-version: ${{ steps.increment_version.outputs.next-version }}
          shortcut-token: ${{ secrets.CLUBHOUSE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}"

      - name: Print release description
        id: print_release_description
        run: echo ${{ steps.prepare_release_description.outputs.current-version }}