name: test-increment-version

on:
  workflow_dispatch:
    inputs:
      current-version-file:
        description: 'The current version file to increment'
        default: 'demo/chem101-server.platform-conventions.gradle'
        required: true
      release-type:
        type: choice
        description: 'The type of release: fix, minor or major'
        required: true
        options:
          - fix
          - minor
          - major

jobs:

  test-increment-version:
    name: Test version increment for ${{github.event.inputs.current-version-file}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Read the branch name
        id: read_current_branch_name
        run: echo ::set-output name=branch-name::${GITHUB_REF#refs/*/}

      - name: Getting current version
        id: read_current_version
        working-directory: .github/actions/read-current-version
        run: |
          bash read-current-version.sh ${{github.event.inputs.current-version-file}}

      - name: Print current version ${{ steps.read_current_version.outputs.current-version }}
        id: print_current_version
        run: echo ${{ steps.read_current_version.outputs.current-version }}

      - name: Increment version ${{ steps.read_current_version.outputs.current-version }}
        id: increment_version
        working-directory: .github/actions/increment-version
        run: |
          bash increment-version.sh ${{ steps.read_current_version.outputs.current-version }} ${{ github.event.inputs.release-type }} 

      - name: Print next (incremented) version ${{ steps.read_current_version.outputs.next-version }}
        id: print_incremented_version
        run: echo ${{ steps.increment_version.outputs.next-version }}

#      - name: Commit next version ${{ steps.increment_version.outputs.next-version }}
#        id: commit_next_version
#        working-directory: .github/actions/commit-next-version
#        run: |
#          bash commit-next-version.sh ${{ steps.read_current_version.outputs.current-version }} ${{ steps.increment_version.outputs.next-version }} ${{github.event.inputs.current-version-file}}
#        env:
#          BRANCH_NAME: ${{ steps.read_current_branch_name.outputs.branch-name }}

      - name: Install JS dependencies
        working-directory: .github/actions/shortcut-notify-next-version
        run: npm i babel-cli -g
        env:
          NODE_AUTH_TOKEN: ""

      - name: Shortcut notification for version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/actions/shortcut-notify-next-version/main.js "${{ steps.read_current_version.outputs.current-version }}" "${{ steps.increment_version.outputs.next-version }}" "${{secrets.CLUBHOUSE_TOKEN}}" "${{secrets.GITHUB_TOKEN}}"