name: test-increment-version

on:
  workflow_dispatch:
    inputs:
      current-version-file:
        description: 'The current version file to increment'
        default: 'demo/chem101-server.platform-conventions.gradle'
        required: true
      version-fragment:
        type: choice
        description: 'The type of release: fix, minor or major'
        required: true
        options:
          - fix
          - minor
          - major

jobs:

  prepare_release:
    name: Prepare release
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history for all tags and branches

      # New release version

      - name: "Step 1/8: Read Branch Name"
        id: read_current_branch_name
        run: echo ::set-output name=branch-name::${GITHUB_REF#refs/*/}

      - name: "Step 2/8: Read Current Version"
        id: read_current_version
        uses: ./.github/actions/read-current-version/
        with:
          current-version-file: ${{github.event.inputs.current-version-file}}

      - name: "Step 3/8: Increment Version ${{ steps.read_current_version.outputs.current-version }}"
        id: increment_version
        uses: ./.github/actions/increment-version
        with:
          current-version: ${{ steps.read_current_version.outputs.current-version }}
          version-fragment: ${{ github.event.inputs.version-fragment }}

      - name: "Step 4/8: Commit Next Version ${{ steps.increment_version.outputs.next-version }}"
        id: commit_next_version
        uses: ./.github/actions/commit-next-version
        with:
          current-version: ${{ steps.read_current_version.outputs.current-version }}
          next-version: ${{ steps.increment_version.outputs.next-version }}
          current-version-file: ${{github.event.inputs.current-version-file}}
        env:
          BRANCH_NAME: ${{ steps.read_current_branch_name.outputs.branch-name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ github.owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}

        # Notification

      - name: Print release description
        id: print_release_description
        run: echo ${{ steps.prepare_release_description.outputs.deployment-description }}