name: test-increment-version

on:
  workflow_dispatch:
    inputs:
      current-version-file:
        description: 'The current version file to increment'
        default: 'buildSrc/src/main/groovy/chem101-server.platform-conventions.gradle'
        required: true
      version-fragment:
        type: choice
        description: 'The type of release: fix, minor or major'
        required: true
        options:
          - fix
          - minor
          - major

jobs:

  prepare_release:
    name: Prepare release
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history for all tags and branches

      # New release version

      - name: "Step 1/8: Read Branch Name"
        id: read_current_branch_name
        run: echo ::set-output name=branch-name::${GITHUB_REF#refs/*/}

      - name: "Step 2/8: Read Current Version"
        id: read_current_version
        uses: ./.github/actions/read-current-version/
        with:
          current-version-file: ${{github.event.inputs.current-version-file}}

      - name: "Step 3/8: Increment Version ${{ steps.read_current_version.outputs.current-version }}"
        id: increment_version
        uses: ./.github/actions/increment-version
        with:
          current-version: ${{ steps.read_current_version.outputs.current-version }}
          version-fragment: ${{ github.event.inputs.version-fragment }}

      - name: "Step 4/8: Commit Next Version ${{ steps.increment_version.outputs.next-version }}"
        id: commit_next_version
        uses: ./.github/actions/commit-next-version
        with:
          current-version: ${{ steps.read_current_version.outputs.current-version }}
          next-version: ${{ steps.increment_version.outputs.next-version }}
          current-version-file: ${{github.event.inputs.current-version-file}}
        env:
          BRANCH_NAME: ${{ steps.read_current_branch_name.outputs.branch-name }}
          BOT_TOKEN_REPO_ALL: ${{ secrets.BOT_TOKEN_REPO_ALL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ github.owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}

        # Notification

      - name: "Step 7/8: Notify Shortcut ${{ steps.increment_version.outputs.next-version }}"
        id: prepare_release_description
        uses: ./.github/actions/shortcut-notify-next-version/
        with:
          branch-name: ${{ steps.read_current_branch_name.outputs.branch-name }}
          current-version: ${{ steps.read_current_version.outputs.current-version }}
          next-version: ${{ steps.increment_version.outputs.next-version }}
          shortcut-token: ${{ secrets.CLUBHOUSE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Step 8/8: Notify Slack ${{ steps.increment_version.outputs.next-version }}"
        id: send_release_description
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          config: .github/config/slack-notify-next-version/slack.yml
          channel: '#engineering-deploys'
          text: ${{ steps.prepare_release_description.outputs.deployment-description }}
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ENGINEERING_DEPLOYS_WEBHOOK_URL }}
