name: test-increment-version

on:
  workflow_dispatch:
    inputs:
      current-version-file:
        description: 'The current version file to increment'
        default: 'chem101-server.platform-conventions.gradle'
        required: true


jobs:

  test-increment-version:
    name: Test version increment for ${{github.event.inputs.current-version-file}}
    runs-on: alpine-latest

    steps:
      - uses: actions/checkout@v2
      - name: Getting current version
        id: read_current_version
        working-directory: .github/read-current-version
        with:
          current-version-file: ${{github.event.inputs.current-version-file}}
        run: | 
          bash read-current-version.sh ${{github.event.inputs.current-version-file}}

      - name: Print current version
        run: echo ${{ steps.read_current_version.outputs.current-version }}
