name: test-increment-version

on:
  workflow_dispatch:
    inputs:
      current-version-file:
        description: 'The current version file to increment'
        required: true


jobs:

  test-increment-version:
    name: Test version increment for ${{chem101-server.platform-conventions.gradle}}
    runs-on: alpine-latest

    steps:
      - uses: actions/checkout@v2
      - name: Getting current version
        id: read_current_version
        with:
          current-version-file: ${{ github.event.inputs.branch }}
        run:
          shell: bash
          working-directory: .github/read-current-version

      - name: Print current version
        run: echo ${{ steps.read_current_version.outputs.current-version }}
